---
## This configuration file maps RV-C Data Group Numbers (DGNs) and Instance IDs
## to unique entity IDs, human-readable names, and suggested areas.
## It's designed to provide metadata for a WebSocket API serving RV-C device states,
## allowing various clients (including Home Assistant) to integrate.
## Based on a 2021 Entegra Aspire 44R, adapt for your specific coach.
##
## Structure:
## - Top Level: DGN (hexadecimal string, e.g., "1FEDA")
##   - Second Level: Instance ID (string, e.g., "25", or "default")
##     - Third Level: A list containing one configuration dictionary per device.
##
## Fields:
##   - entity_id: A unique, machine-readable identifier (lowercase, underscores). REQUIRED.
##   - friendly_name: A human-readable name for display. REQUIRED.
##   - suggested_area: The suggested location/area of the device. OPTIONAL.
##   - device_type: A general classification (e.g., 'light', 'lock', 'sensor', 'switch'). REQUIRED.
##   - capabilities: A list of actions or states the device supports (e.g., ['on_off', 'brightness']). REQUIRED.
##   - (Other fields): Can be added for specific device types or future use by the WebSocket service.
##
## Use the 'default' instance if a specific instance isn't found or isn't relevant.
## YAML anchors (&) and aliases (*) can be used for templating common fields.

# Template section for reusable parameters
templates:
  # Template for a simple on/off light
  switchable_light: &switchable_light
    device_type: light
    capabilities: [on_off]

  # Template for a dimmable light
  dimmable_light: &dimmable_light
    device_type: light
    capabilities: [on_off, brightness]

  # Template for a lock
  lock: &lock
    device_type: lock
    capabilities: [lock_unlock]

# Door Locks (DGN 1FEDB likely corresponds to RVC_LOCK_COMMAND)
# ADDING LIGHTS HERE FOR SENDING COMMANDS
1FEDB:
  default:
    - entity_id: entrance_door_lock
      friendly_name: Entrance Door Lock
      suggested_area: Entrance
      interface: can1
      status_dgn: '1FEDC'
      group_mask: '0x7C'
      <<: *lock

  # Interior Lights (Moved from 1FEDA)
  25:
    - entity_id: bedroom_ceiling_light
      friendly_name: Bedroom Ceiling Light
      suggested_area: Bedroom
      interface: can1
      status_dgn: '1FEDA'
      group_mask: '0x7C'
      <<: *dimmable_light
  27:
    - entity_id: bedroom_accent_light
      friendly_name: Bedroom Accent Light
      suggested_area: Bedroom
      interface: can1
      status_dgn: '1FEDA'
      group_mask: '0x7C'
      <<: *dimmable_light
  28:
    - entity_id: bedroom_vanity_light
      friendly_name: Bedroom Vanity Light
      suggested_area: Bedroom
      interface: can1
      status_dgn: '1FEDA'
      group_mask: '0x7C'
      <<: *dimmable_light
  29:
    - entity_id: bedroom_reading_light
      friendly_name: Bedroom Reading Light
      suggested_area: Bedroom
      interface: can1
      status_dgn: '1FEDA'
      group_mask: '0x7C'
      <<: *dimmable_light
  30:
    - entity_id: master_bath_ceiling_light
      friendly_name: Master Bathroom Ceiling Light
      suggested_area: Master Bathroom
      interface: can1
      status_dgn: '1FEDA'
      group_mask: '0x7C'
      <<: *dimmable_light
  31:
    - entity_id: master_bath_lav_light
      friendly_name: Master Bathroom Lavatory Light
      suggested_area: Master Bathroom
      interface: can1
      status_dgn: '1FEDA'
      group_mask: '0x7C'
      <<: *dimmable_light
  32:
    - entity_id: master_bath_accent_light
      friendly_name: Master Bathroom Accent Light
      suggested_area: Master Bathroom
      interface: can1
      status_dgn: '1FEDA'
      group_mask: '0x7C'
      <<: *dimmable_light
  33:
    - entity_id: mid_bath_ceiling_light
      friendly_name: Mid Bathroom Ceiling Light
      suggested_area: Mid Bathroom
      interface: can1
      status_dgn: '1FEDA'
      group_mask: '0x7C'
      <<: *dimmable_light
  34:
    - entity_id: mid_bath_accent_light
      friendly_name: Mid Bathroom Accent Light
      suggested_area: Mid Bathroom
      interface: can1
      status_dgn: '1FEDA'
      group_mask: '0x7C'
      <<: *dimmable_light
  35:
    - entity_id: entrance_ceiling_light
      friendly_name: Entrance Ceiling Light
      suggested_area: Entrance
      interface: can1
      status_dgn: '1FEDA'
      group_mask: '0x7C'
      <<: *dimmable_light
  37:
    - entity_id: main_ceiling_light
      friendly_name: Main Ceiling Light
      suggested_area: Main Living Area
      interface: can1
      status_dgn: '1FEDA'
      group_mask: '0x7C'
      <<: *dimmable_light
  38:
    - entity_id: bedroom_courtesy_light
      friendly_name: Bedroom Courtesy Light
      suggested_area: Master Bedroom
      interface: can1
      status_dgn: '1FEDA'
      group_mask: '0x7C'
      <<: *dimmable_light
  39:
    - entity_id: main_ceiling_accent_light
      friendly_name: Main Ceiling Accent Light
      suggested_area: Main Living Area
      interface: can1
      status_dgn: '1FEDA'
      group_mask: '0x7C'
      <<: *dimmable_light
  41:
    - entity_id: main_driver_side_ceiling_light
      friendly_name: Main Driver Side Ceiling Light
      suggested_area: Main Living Area
      interface: can1
      status_dgn: '1FEDA'
      group_mask: '0x7C'
      <<: *dimmable_light
  42:
    - entity_id: main_passenger_side_ceiling_light
      friendly_name: Main Passenger Side Ceiling Light
      suggested_area: Main Living Area
      interface: can1
      status_dgn: '1FEDA'
      group_mask: '0x7C'
      <<: *dimmable_light
  43:
    - entity_id: main_driver_side_slide_light
      friendly_name: Main Driver Side Slide Light
      suggested_area: Main Living Area
      interface: can1
      status_dgn: '1FEDA'
      group_mask: '0x7C'
      <<: *dimmable_light
  45:
    - entity_id: main_dinette_light
      friendly_name: Main Dinette Light
      suggested_area: Main Living Area
      interface: can1
      status_dgn: '1FEDA'
      group_mask: '0x7C'
      <<: *dimmable_light
  46:
    - entity_id: main_sink_light
      friendly_name: Main Sink Light
      suggested_area: Main Living Area
      interface: can1
      status_dgn: '1FEDA'
      group_mask: '0x7C'
      <<: *dimmable_light
  47:
    - entity_id: main_midship_light
      friendly_name: Main Midship Light
      suggested_area: Main Living Area
      interface: can1
      status_dgn: '1FEDA'
      group_mask: '0x7C'
      <<: *dimmable_light

  # Exterior Lights (Moved from 1FEDA)
  51:
    - entity_id: exterior_driver_side_awning_light
      friendly_name: Exterior Driver Side Awning Light
      suggested_area: Exterior
      interface: can1
      status_dgn: '1FEDA'
      group_mask: '0x7C'
      <<: *switchable_light
  52:
    - entity_id: exterior_passenger_side_awning_light
      friendly_name: Exterior Passenger Side Awning Light
      suggested_area: Exterior
      interface: can1
      status_dgn: '1FEDA'
      group_mask: '0x7C'
      <<: *switchable_light
  53:
    - entity_id: basement_cargo_light
      friendly_name: Basement Cargo Light
      suggested_area: Basement
      interface: can1
      status_dgn: '1FEDA'
      group_mask: '0x7C'
      <<: *switchable_light
  54:
    - entity_id: exterior_under_slide_light
      friendly_name: Exterior Under Slide Light
      suggested_area: Exterior
      interface: can1
      status_dgn: '1FEDA'
      group_mask: '0x7C'
      <<: *switchable_light
  57:
    - entity_id: exterior_driver_side_security_light
      friendly_name: Exterior Driver Side Security Light
      suggested_area: Exterior
      interface: can1
      status_dgn: '1FEDA'
      group_mask: '0x7C'
      <<: *switchable_light
  58:
    - entity_id: exterior_passenger_side_security_light
      friendly_name: Exterior Passenger Side Security Light
      suggested_area: Exterior
      interface: can1
      status_dgn: '1FEDA'
      group_mask: '0x7C'
      <<: *switchable_light
  59:
    - entity_id: exterior_motion_light
      friendly_name: Exterior Motion Light
      suggested_area: Exterior
      interface: can1
      status_dgn: '1FEDA'
      group_mask: '0x7C'
      <<: *switchable_light
  60:
    - entity_id: exterior_porch_light
      friendly_name: Exterior Porch Light
      suggested_area: Exterior
      interface: can1
      status_dgn: '1FEDA'
      group_mask: '0x7C'
      <<: *switchable_light

# Lock Status (DGN 1FEDC likely corresponds to RVC_LOCK_STATUS)
1FEDC:
  default:
    - entity_id: entrance_door_lock
      friendly_name: Entrance Door Lock
      suggested_area: Entrance
      <<: *lock
