---
## This configuration file maps RV-C Data Group Numbers (DGNs) and Instance IDs
## to unique entity IDs, human-readable names, and suggested areas.
## It's designed to provide metadata for a WebSocket API serving RV-C device states,
## allowing various clients (including Home Assistant) to integrate.
## Based on a 2021 Entegra Aspire 44R, adapt for your specific coach.
##
## Structure:
## - Top Level: DGN (hexadecimal string, e.g., "1FEDA")
##   - Second Level: Instance ID (string, e.g., "25", or "default")
##     - Third Level: A list containing one configuration dictionary per device.
##
## Fields:
##   - entity_id: A unique, machine-readable identifier (lowercase, underscores). REQUIRED.
##   - friendly_name: A human-readable name for display. REQUIRED.
##   - suggested_area: The suggested location/area of the device. OPTIONAL.
##   - device_type: A general classification (e.g., 'light', 'lock', 'sensor', 'switch'). REQUIRED.
##   - capabilities: A list of actions or states the device supports (e.g., ['on_off', 'brightness']). REQUIRED.
##   - (Other fields): Can be added for specific device types or future use by the WebSocket service.
##
## Use the 'default' instance if a specific instance isn't found or isn't relevant.
## YAML anchors (&) and aliases (*) can be used for templating common fields.

# Template section for reusable parameters
templates:
  # Template for a simple on/off light
  switchable_light: &switchable_light
    device_type: light
    capabilities: [on_off]

  # Template for a dimmable light
  dimmable_light: &dimmable_light
    device_type: light
    capabilities: [on_off, brightness]

  # Template for a lock
  lock: &lock
    device_type: lock
    capabilities: [lock_unlock]

# Interior Lights (DGN 1FEDA likely corresponds to RVC_LIGHT_COMMAND)
1FEDA:
  25:
    - entity_id: bedroom_ceiling_light # Renamed from ha_name
      friendly_name: Bedroom Ceiling Light
      suggested_area: Bedroom
      <<: *dimmable_light # Use new template
  27:
    - entity_id: bedroom_accent_light # Renamed
      friendly_name: Bedroom Accent Light
      suggested_area: Bedroom
      <<: *dimmable_light
  28:
    - entity_id: bedroom_vanity_light # Renamed
      friendly_name: Bedroom Vanity Light
      suggested_area: Bedroom
      <<: *dimmable_light
  29:
    - entity_id: bedroom_reading_light # Renamed
      friendly_name: Bedroom Reading Light
      suggested_area: Bedroom
      <<: *dimmable_light
  30:
    - entity_id: master_bath_ceiling_light # Renamed
      friendly_name: Master Bathroom Ceiling Light
      suggested_area: Master Bathroom
      <<: *dimmable_light
  31:
    - entity_id: master_bath_lav_light # Renamed
      friendly_name: Master Bathroom Lavatory Light
      suggested_area: Master Bathroom
      <<: *dimmable_light
  32:
    - entity_id: master_bath_accent_light # Renamed
      friendly_name: Master Bathroom Accent Light
      suggested_area: Master Bathroom
      <<: *dimmable_light
  33:
    - entity_id: mid_bath_ceiling_light # Renamed
      friendly_name: Mid Bathroom Ceiling Light
      suggested_area: Mid Bathroom
      <<: *dimmable_light
  34:
    - entity_id: mid_bath_accent_light # Renamed
      friendly_name: Mid Bathroom Accent Light
      suggested_area: Mid Bathroom
      <<: *dimmable_light
  35:
    - entity_id: entrance_ceiling_light # Renamed
      friendly_name: Entrance Ceiling Light
      suggested_area: Entrance
      <<: *dimmable_light
  37:
    - entity_id: main_ceiling_light # Renamed
      friendly_name: Main Ceiling Light
      suggested_area: Main Living Area
      <<: *dimmable_light
  38:
    - entity_id: bedroom_courtesy_light # Renamed
      friendly_name: Bedroom Courtesy Light
      suggested_area: Master Bedroom
      <<: *dimmable_light # Assuming dimmable, adjust if not
  39:
    - entity_id: main_ceiling_accent_light # Renamed
      friendly_name: Main Ceiling Accent Light
      suggested_area: Main Living Area
      <<: *dimmable_light
  41:
    - entity_id: main_driver_side_ceiling_light # Renamed
      friendly_name: Main Driver Side Ceiling Light
      suggested_area: Main Living Area
      <<: *dimmable_light
  42:
    - entity_id: main_passenger_side_ceiling_light # Renamed
      friendly_name: Main Passenger Side Ceiling Light
      suggested_area: Main Living Area
      <<: *dimmable_light
  43:
    - entity_id: main_driver_side_slide_light # Renamed
      friendly_name: Main Driver Side Slide Light
      suggested_area: Main Living Area
      <<: *dimmable_light
  45:
    - entity_id: main_dinette_light # Renamed
      friendly_name: Main Dinette Light
      suggested_area: Main Living Area
      <<: *dimmable_light
  46:
    - entity_id: main_sink_light # Renamed
      friendly_name: Main Sink Light
      suggested_area: Main Living Area
      <<: *dimmable_light
  47:
    - entity_id: main_midship_light # Renamed
      friendly_name: Main Midship Light
      suggested_area: Main Living Area
      <<: *dimmable_light

# Exterior Lights (Also likely DGN 1FEDA)
  51:
    - entity_id: exterior_driver_side_awning_light # Renamed
      friendly_name: Exterior Driver Side Awning Light
      suggested_area: Exterior
      <<: *switchable_light # Use new template
  52:
    - entity_id: exterior_passenger_side_awning_light # Renamed
      friendly_name: Exterior Passenger Side Awning Light
      suggested_area: Exterior
      <<: *switchable_light
  53:
    - entity_id: basement_cargo_light # Renamed
      friendly_name: Basement Cargo Light
      suggested_area: Basement
      <<: *switchable_light
  54:
    - entity_id: exterior_under_slide_light # Renamed
      friendly_name: Exterior Under Slide Light
      suggested_area: Exterior
      <<: *switchable_light
  57:
    - entity_id: exterior_driver_side_security_light # Renamed
      friendly_name: Exterior Driver Side Security Light
      suggested_area: Exterior
      <<: *switchable_light
  58:
    - entity_id: exterior_passenger_side_security_light # Renamed
      friendly_name: Exterior Passenger Side Security Light
      suggested_area: Exterior
      <<: *switchable_light
  59:
    - entity_id: exterior_motion_light # Renamed
      friendly_name: Exterior Motion Light
      suggested_area: Exterior
      <<: *switchable_light
  60:
    - entity_id: exterior_porch_light # Renamed
      friendly_name: Exterior Porch Light
      suggested_area: Exterior
      <<: *switchable_light

# Light Status (DGN 1FED9 likely corresponds to RVC_LIGHT_STATUS)
# Mirrors the command entries to map status messages back to the same entities
1FED9:
  25:
    - entity_id: bedroom_ceiling_light
      friendly_name: Bedroom Ceiling Light
      suggested_area: Bedroom
      <<: *dimmable_light
  27:
    - entity_id: bedroom_accent_light
      friendly_name: Bedroom Accent Light
      suggested_area: Bedroom
      <<: *dimmable_light
  28:
    - entity_id: bedroom_vanity_light
      friendly_name: Bedroom Vanity Light
      suggested_area: Bedroom
      <<: *dimmable_light
  29:
    - entity_id: bedroom_reading_light
      friendly_name: Bedroom Reading Light
      suggested_area: Bedroom
      <<: *dimmable_light
  30:
    - entity_id: master_bath_ceiling_light
      friendly_name: Master Bathroom Ceiling Light
      suggested_area: Master Bathroom
      <<: *dimmable_light
  31:
    - entity_id: master_bath_lav_light
      friendly_name: Master Bathroom Lavatory Light
      suggested_area: Master Bathroom
      <<: *dimmable_light
  32:
    - entity_id: master_bath_accent_light
      friendly_name: Master Bathroom Accent Light
      suggested_area: Master Bathroom
      <<: *dimmable_light
  33:
    - entity_id: mid_bath_ceiling_light
      friendly_name: Mid Bathroom Ceiling Light
      suggested_area: Mid Bathroom
      <<: *dimmable_light
  34:
    - entity_id: mid_bath_accent_light
      friendly_name: Mid Bathroom Accent Light
      suggested_area: Mid Bathroom
      <<: *dimmable_light
  35:
    - entity_id: entrance_ceiling_light
      friendly_name: Entrance Ceiling Light
      suggested_area: Entrance
      <<: *dimmable_light
  37:
    - entity_id: main_ceiling_light
      friendly_name: Main Ceiling Light
      suggested_area: Main Living Area
      <<: *dimmable_light
  38:
    - entity_id: bedroom_courtesy_light
      friendly_name: Bedroom Courtesy Light
      suggested_area: Master Bedroom
      <<: *dimmable_light # Assuming dimmable, adjust if not
  39:
    - entity_id: main_ceiling_accent_light
      friendly_name: Main Ceiling Accent Light
      suggested_area: Main Living Area
      <<: *dimmable_light
  41:
    - entity_id: main_driver_side_ceiling_light
      friendly_name: Main Driver Side Ceiling Light
      suggested_area: Main Living Area
      <<: *dimmable_light
  42:
    - entity_id: main_passenger_side_ceiling_light
      friendly_name: Main Passenger Side Ceiling Light
      suggested_area: Main Living Area
      <<: *dimmable_light
  43:
    - entity_id: main_driver_side_slide_light
      friendly_name: Main Driver Side Slide Light
      suggested_area: Main Living Area
      <<: *dimmable_light
  45:
    - entity_id: main_dinette_light
      friendly_name: Main Dinette Light
      suggested_area: Main Living Area
      <<: *dimmable_light
  46:
    - entity_id: main_sink_light
      friendly_name: Main Sink Light
      suggested_area: Main Living Area
      <<: *dimmable_light
  47:
    - entity_id: main_midship_light
      friendly_name: Main Midship Light
      suggested_area: Main Living Area
      <<: *dimmable_light
  51:
    - entity_id: exterior_driver_side_awning_light
      friendly_name: Exterior Driver Side Awning Light
      suggested_area: Exterior
      <<: *switchable_light
  52:
    - entity_id: exterior_passenger_side_awning_light
      friendly_name: Exterior Passenger Side Awning Light
      suggested_area: Exterior
      <<: *switchable_light
  53:
    - entity_id: basement_cargo_light
      friendly_name: Basement Cargo Light
      suggested_area: Basement
      <<: *switchable_light
  54:
    - entity_id: exterior_under_slide_light
      friendly_name: Exterior Under Slide Light
      suggested_area: Exterior
      <<: *switchable_light
  57:
    - entity_id: exterior_driver_side_security_light
      friendly_name: Exterior Driver Side Security Light
      suggested_area: Exterior
      <<: *switchable_light
  58:
    - entity_id: exterior_passenger_side_security_light
      friendly_name: Exterior Passenger Side Security Light
      suggested_area: Exterior
      <<: *switchable_light
  59:
    - entity_id: exterior_motion_light
      friendly_name: Exterior Motion Light
      suggested_area: Exterior
      <<: *switchable_light
  60:
    - entity_id: exterior_porch_light
      friendly_name: Exterior Porch Light
      suggested_area: Exterior
      <<: *switchable_light

# Door Locks (DGN 1FEDB likely corresponds to RVC_LOCK_COMMAND)
1FEDB:
  default: # Assuming only one entrance door lock
    - entity_id: entrance_door_lock # Renamed
      friendly_name: Entrance Door Lock
      suggested_area: Entrance
      <<: *lock # Use new template

# Lock Status (DGN 1FEDC likely corresponds to RVC_LOCK_STATUS)
# Mirrors the command entry to map status messages back to the same entity
1FEDC:
  default: # Assuming only one entrance door lock status
    - entity_id: entrance_door_lock
      friendly_name: Entrance Door Lock
      suggested_area: Entrance
      <<: *lock # Use the same lock template

# --- Commented out devices ---
# Review and uncomment/update these if needed for your coach,
# assigning appropriate entity_id, device_type, and capabilities.

# Example: Tank Sensor (Hypothetical DGN/Instance)
# 1FFAB:
#   1: # Fresh water tank instance 1
#     - entity_id: fresh_water_tank
#       friendly_name: Fresh Water Tank
#       suggested_area: Wet Bay
#       device_type: sensor
#       capabilities: [level] # Indicates it reports a level
#       unit_of_measurement: "%" # Optional hint for clients

# Example: Generator Status (Hypothetical DGN/Instance)
# 1FFDC:
#   default:
#     - entity_id: generator_status
#       friendly_name: Generator Status
#       suggested_area: Generator
#       device_type: sensor # Or maybe 'binary_sensor' if just on/off
#       capabilities: [running_state, hours] # Example capabilities

# (Keep the rest of the previously commented out DGNs below for reference)
# 17F00:
#   default:
#     - entity_id: "general_reset" # Renamed
#       friendly_name: "General Reset"
#       device_type: switch # Example
#       capabilities: [on_off] # Example

# 1FED8:
#   default:
#     - entity_id: "configuration_status" # Renamed
#       friendly_name: "Configuration Status"
#       device_type: sensor # Example
#       capabilities: [status_text] # Example

# 1FFDF:
#   default:
#     - entity_id: "generator_ac_status_1" # Renamed
#       friendly_name: "Generator AC Status 1"
#       device_type: sensor # Example
#       capabilities: [voltage, current, frequency] # Example

# 1FFDE:
#   default:
#     - entity_id: "generator_ac_status_2" # Renamed
#       friendly_name: "Generator AC Status 2"
#       device_type: sensor # Example
#       capabilities: [voltage, current, frequency] # Example

# 1FFDD:
#   default:
#     - entity_id: "generator_ac_status_3" # Renamed
#       friendly_name: "Generator AC Status 3"
#       device_type: sensor # Example
#       capabilities: [voltage, current, frequency] # Example

# 1FF94:
#   default:
#     - entity_id: "generator_ac_status_4" # Renamed
#       friendly_name: "Generator AC Status 4"
#       device_type: sensor # Example
#       capabilities: [voltage, current, frequency] # Example

# 1FEC6:
#   default:
#     - entity_id: "generator_dc_status_1" # Renamed
#       friendly_name: "Generator DC Status 1"
#       device_type: sensor # Example
#       capabilities: [voltage, current] # Example

# 1FEC5:
#   default:
#     - entity_id: "generator_dc_configuration_status" # Renamed
#       friendly_name: "Generator DC Configuration Status"
#       device_type: sensor # Example
#       capabilities: [status_text] # Example

# 1FEC4:
#   default:
#     - entity_id: "generator_dc_command" # Renamed
#       friendly_name: "Generator DC Command"
#       device_type: sensor # Example - or maybe 'switch' if controllable?
#       capabilities: [command_status] # Example

# 1FEC3:
#   default:
#     - entity_id: "generator_dc_configuration_command" # Renamed
#       friendly_name: "Generator DC Configuration Command"
#       device_type: sensor # Example
#       capabilities: [command_status] # Example

# 1FEC2:
#   default:
#     - entity_id: "generator_dc_equalization_status" # Renamed
#       friendly_name: "Generator DC Equalization Status"
#       device_type: sensor # Example
#       capabilities: [status_text] # Example

# 1FEC1:
#   default:
#     - entity_id: "generator_dc_equalization_configuration_status" # Renamed
#       friendly_name: "Generator DC Equalization Configuration Status"
#       device_type: sensor # Example
#       capabilities: [status_text] # Example

# 1FEC0:
#   default:
#     - entity_id: "generator_dc_equalization_configuration_command" # Renamed
#       friendly_name: "Generator DC Equalization Configuration Command"
#       device_type: sensor # Example
#       capabilities: [command_status] # Example

# 1FFDC:
#   default:
#     - entity_id: "generator_status_1" # Renamed
#       friendly_name: "Generator Status 1"
#       device_type: sensor # Example
#       capabilities: [status_text] # Example

# 1FFDB:
#   default:
#     - entity_id: "generator_status_2" # Renamed
#       friendly_name: "Generator Status 2"
#       device_type: sensor # Example
#       capabilities: [temperature_shutdown_status] # Example

# 1FFDA:
#   default:
#     - entity_id: "generator_command" # Renamed
#       friendly_name: "Generator Command"
#       device_type: sensor # Example - or 'switch' if controllable?
#       capabilities: [command_status] # Example

# 1FFD9:
#   default:
#     - entity_id: "generator_start_config_status" # Renamed
#       friendly_name: "Generator Start Config Status"
#       device_type: sensor # Example
#       capabilities: [status_text] # Example

# 1FFD8:
#   default:
#     - entity_id: "generator_start_config_command" # Renamed
#       friendly_name: "Generator Start Config Command"
#       device_type: sensor # Example
#       capabilities: [command_status] # Example
