name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-and-check:
    runs-on: ubuntu-22.04-arm    # ← ARM64 GitHub‑hosted runner

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix (flakes)
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Enable Cachix (fetch + push)
        uses: cachix/cachix-action@v16
        with:
          name: carpenike
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Run flake checks
        run: nix flake check

      - name: Build NixOS system (ARM64)
        run: |
          nix build --system aarch64-linux \
            .#nixosConfigurations.nixpi.config.system.build.toplevel
