name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix (flakes)
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Load Cachix cache
        uses: cachix/cachix-action@v15
        with:
          name: carpenike
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Run flake checks
        run: nix flake check

      - name: Build NixOS system
        run: nix build .#nixosConfigurations.nixpi.config.system.build.toplevel
