name: Update Flake.lock

on:
  schedule:
    - cron: '0 6 * * *'   # every day at 06:00 UTC
  workflow_dispatch: {}   # allows manual “Run workflow”

jobs:
  bump-lock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix (flakes)
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Load Cachix cache
        uses: cachix/cachix-action@v15
        with:
          name: your-cache-name
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}

      - name: Update flake.lock
        run: nix flake update --recreate-lock-file

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "chore: bump flake.lock"
          git push
