name: Lint & Format

on:
  pull_request:
    paths:
      - '**/*.nix'
      - 'flake.lock'
  push:
    branches: [ main ]
    paths:
      - '**/*.nix'
      - 'flake.lock'

jobs:
  format-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix (flakes)
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: nixpkgs-fmt check
        run: nix run nixpkgs#nixfmt -- --check **/*.nix

      - name: nix-linter
        run: nix run github:nix-community/nix-linter -- lint .
